end/demo2/blog/apps/blogapp/urls.py
from  django.conf.urls import url,include
from . import views

app_name='blogapp'

urlpatterns=[

    url(r'^$',views.index,name='index'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^favicon.ico/$',views.favicon),
    url(r'^search/', include('haystack.urls')),
]

end/demo2/blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from .settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    path("",include('blogapp.urls',namespace='blogapp')),

]

end/demo2/blog/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

end/demo2/blog/apps/blogapp/models.py
from django.db import models
#  导入父文本字段类
from DjangoUeditor.models import UEditorField

# Create your models here.
class Ads(models.Model):
    # 使用图片字段  需要安装pillow
    img = models.ImageField(upload_to="ads")
    desc = models.CharField(max_length=20, null=True, blank=True, verbose_name="图片描述")
    def __str__(self):
        return self.desc

class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name="分类名")
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name="标签名",default=None)

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name="文章标题")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")
    author = models.CharField(max_length=10, verbose_name="作者")
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")
    # body = models.TextField(verbose_name="正文")
    #  使用百度UEditor
    body =UEditorField(imagePath="imgs/",width="100%")
    tag = models.ManyToManyField(Tag)
    def __str__(self):
        return self.title

class Comment(models.Model):
    name=models.CharField(max_length=20,verbose_name="评论人")
    url = models.URLField(default="http://yxc.com",verbose_name="个人主页")
    email = models.EmailField(default='1335909103@qq.com',verbose_name='个人邮箱')
    body = models.CharField(max_length=500,verbose_name='评论内容')
    create_time=models.DateTimeField(auto_now_add=True,verbose_name="评论时间")
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="所属文章")

    def __str__(self):
        return self.name

end/demo2/blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>

<body>

<div id="site-header">
	<div class="container">
		<div class="row">
				<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
								<h1><a href="index.html"><b>博客实战</b></a></h1>
						</div>
				</div><!-- col-md-4 -->
				<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
								<div class="navbar-header">
										<button type="button" id="trigger-overlay" class="navbar-toggle">
												<span class="ion-navicon"></span>
										</button>
								</div>

								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
												<li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
												<li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
												<li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
										</ul>
								</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
								<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
								<div id="search-form" class="search-form">
										<form method='get' action="/search/" target="_blank">
                                            <input type="text" name="q">
                                            <input type="submit" value="查询">
                                        </form>
								</div>
						</div>
				</div><!-- col-md-8 -->
		</div>
	</div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            {% block main %}
            {% endblock %}
            {% block aside %}
            {% endblock %}

        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

end/demo2/blog/templates/base2.html
{% extends 'base.html' %}
{% load myfun %}
{% block aside %}
<aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_latestarticles 5 as latestarticles %}
                    <ul>
                        {% for article in latestarticles %}
                        <li>
                            <a href="{% url 'blogapp:detail' article.id %}">{{article.title}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    {% get_latesdates as latesdates %}

                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% for date in latesdates %}
                        <li>
                            <a href="/?type=date&year={{date.year}}&month={{date.month}}">{{date.year}} 年 {{date.month}} 月</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categorys as categorys %}

                    <ul>
                        {% for c in categorys %}
                        <li>
                            <a href="/?type=category&category_id={{c.id}}">{{c.name}}<span class="post-count">({{c.article_set.count}})</span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% gettags as tags %}
                    <ul>
                        {% for tag in tags %}
                        <li>
                            <a href="/?type=tag&tag_id={{tag.id}}">{{tag.name}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
{% endblock %}

end/demo2/blog/templates/contact.html
{% extends 'base.html' %}
{% block title %}
    博客实战联系
{% endblock %}
{% block main %}
  <main class="col-md-12">
            	<h1 class="page-title">Contact</h1>
            	<article class="post">
            		<div class="entry-content clearfix">
            			<form action="#" method="post" class="contact-form">
            				<div class="row">
            					<div class="col-md-6 col-md-offset-3">
            						<input type="text" name="name" placeholder="名字" required>
            						<input type="email" name="email" placeholder="邮箱" required>
            						<textarea name="message" rows="7" placeholder="建议" required></textarea>
            						<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>发送</span></button>
            					</div>
            				</div>	<!-- row -->
            			</form>
            		</div>
            	</article>
            </main>
{% endblock %}
{% block aside %}

{% endblock %}

end/demo2/blog/templates/full-width.html
<!DOCTYPE html>
<html>
<head>
    <title>博客实战</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="css/pace.css">
    <link rel="stylesheet" href="css/custom.css">

    <!-- js -->
    <script src="js/jquery-2.1.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/pace.min.js"></script>
    <script src="js/modernizr.custom.js"></script>
</head>

<body>

<div id="site-header">
	<div class="container">
		<div class="row">
				<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
								<h1><a href="index.html"><b>博客实战</b></a></h1>
						</div>
				</div><!-- col-md-4 -->
				<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
								<div class="navbar-header">
										<button type="button" id="trigger-overlay" class="navbar-toggle">
												<span class="ion-navicon"></span>
										</button>
								</div>

								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
												<li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
												<li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
												<li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
										</ul>
								</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
								<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
								<div id="search-form" class="search-form">
										<form role="search" method="get" id="searchform" action="#">
												<input type="search" placeholder="搜索" required>
												<button type="submit"><span class="ion-ios-search-strong"></span></button>
										</form>
								</div>
						</div>
				</div><!-- col-md-8 -->
		</div>
	</div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
								<article class="post post-1">
								                    <header class="entry-header">
								                        <h1 class="entry-title">
								                            <a href="single.html">Django 博客开发入门教程：前言</a>
								                        </h1>
								                        <div class="entry-meta">
								                            <span class="post-category"><a href="#">Django 博客教程</a></span>
								                            <span class="post-date"><a href="#"><time class="entry-date"
								                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
								                            <span class="post-author"><a href="#">追梦人物</a></span>
								                            <span class="comments-link"><a href="#">4 评论</a></span>
								                            <span class="views-count"><a href="#">588 阅读</a></span>
								                        </div>
								                    </header>
								                    <div class="entry-content clearfix">
								                        <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
								                            开发的技巧...</p>
								                        <div class="read-more cl-effect-14">
								                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
								                        </div>
								                    </div>
								                </article>
								
								                <article class="post post-2">
								                    <header class="entry-header">
								                        <h1 class="entry-title">
								                            <a href="single.html">Django 博客开发入门教程：前言</a>
								                        </h1>
								                        <div class="entry-meta">
								                            <span class="post-category"><a href="#">Django 博客教程</a></span>
								                            <span class="post-date"><a href="#"><time class="entry-date"
								                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
								                            <span class="post-author"><a href="#">追梦人物</a></span>
								                            <span class="comments-link"><a href="#">4 评论</a></span>
								                            <span class="views-count"><a href="#">588 阅读</a></span>
								                        </div>
								                    </header>
								                    <div class="entry-content clearfix">
								                        <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
								                            开发的技巧...</p>
								                        <div class="read-more cl-effect-14">
								                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
								                        </div>
								                    </div>
								                </article>
								
								                <article class="post post-3">
								                    <header class="entry-header">
								                        <h1 class="entry-title">
								                            <a href="single.html">Django 博客开发入门教程：前言</a>
								                        </h1>
								                        <div class="entry-meta">
								                            <span class="post-category"><a href="#">Django 博客教程</a></span>
								                            <span class="post-date"><a href="#"><time class="entry-date"
								                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
								                            <span class="post-author"><a href="#">追梦人物</a></span>
								                            <span class="comments-link"><a href="#">4 评论</a></span>
								                            <span class="views-count"><a href="#">588 阅读</a></span>
								                        </div>
								                    </header>
								                    <div class="entry-content clearfix">
								                        <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
								                            开发的技巧...</p>
								                        <div class="read-more cl-effect-14">
								                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
								                        </div>
								                    </div>
								                </article>
								
								                <article class="post post-4">
								                    <header class="entry-header">
								                        <h1 class="entry-title">
								                            <a href="single.html">Django 博客开发入门教程：前言</a>
								                        </h1>
								                        <div class="entry-meta">
								                            <span class="post-category"><a href="#">Django 博客教程</a></span>
								                            <span class="post-date"><a href="#"><time class="entry-date"
								                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
								                            <span class="post-author"><a href="#">追梦人物</a></span>
								                            <span class="comments-link"><a href="#">4 评论</a></span>
								                            <span class="views-count"><a href="#">588 阅读</a></span>
								                        </div>
								                    </header>
								                    <div class="entry-content clearfix">
								                        <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django
								                            开发的技巧...</p>
								                        <div class="read-more cl-effect-14">
								                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
								                        </div>
								                    </div>
								                </article>
								                <!-- 简单分页效果
								                <div class="pagination-simple">
								                    <a href="#">上一页</a>
								                    <span class="current">第 6 页 / 共 11 页</span>
								                    <a href="#">下一页</a>
								                </div>
								                -->
								                <div class="pagination">
								                    <ul>
								                        <li><a href="">1</a></li>
								                        <li><a href="">...</a></li>
								                        <li><a href="">4</a></li>
								                        <li><a href="">5</a></li>
								                        <li class="current"><a href="">6</a></li>
								                        <li><a href="">7</a></li>
								                        <li><a href="">8</a></li>
								                        <li><a href="">...</a></li>
								                        <li><a href="">11</a></li>
								                    </ul>
								                </div>
						</main>
            
        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="js/script.js"></script>

</body>
</html>

end/demo2/blog/templates/index.html
{% extends 'base2.html' %}

{% load myfun %}

{% block title %}
    首页
{% endblock %}

{% block main %}
 <main class="col-md-8">

     <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

									<!-- Indicators -->
									<ol class="carousel-indicators">
                                        {% for a in ads %}

                                            {% if forloop.counter0 == 0 %}
                                            <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}" class="active"></li>
                                            {% else %}
                                            <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}"></li>
                                            {% endif %}
                                        {% endfor %}
									</ol>

									<!-- Wrapper for slides -->
									<div class="carousel-inner" role="listbox">
                                        {% for a in ads %}
                                            {% if forloop.counter0 == 0 %}
                                                <div class="item active">
                                                    <img src="/media/{{a.img}}" alt="...">
                                                    <div class="carousel-caption">
                                                        <h1>{{a.desc}}</h1>
                                                    </div>
                                                </div>
                                            {% else %}
                                                <div class="item">
                                                    <img src="/media/{{a.img}}" alt="...">
                                                    <div class="carousel-caption">
                                                        <h1>{{a.desc}}</h1>
                                                    </div>
                                                </div>
                                            {% endif %}
                                        {% endfor %}
									</div>

									<!-- Controls -->
									<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
										<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
										<span class="sr-only">Previous</span>
									</a>
									<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
										<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
										<span class="sr-only">Next</span>
									</a>
								</div>





                {% for a in page.object_list %}
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blogapp:detail' a.id %}">{{a.title}}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{a.category.name}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{a.create_time|date:'Y-m-d'}}</time></a></span>
                            <span class="post-author"><a href="#">{{a.author|authorFormat:"作者"}}</a></span>
                            <span class="comments-link"><a href="#">{{a.comment_set.count}} 评论</a></span>
                            <span class="views-count"><a href="#">{{a.views}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{a.body|safe|truncatechars_html:'5'}}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{% url 'blogapp:detail' a.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% endfor %}
                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination col-md-11">
                    <ul>
                        {% if page.has_previous %}
                        <li class="col-md-2"><a href="?pagenum={{page.previous_page_number}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">上一页</a></li>
                        {% endif %}

                        {% for pn in page.paginator.page_range %}
                            {% if pn == page.number %}
                                <li class="current col-md-1"><a href="?pagenum={{pn}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">{{pn}}</a></li>
                            {% else %}
                                <li class="col-md-1"><a href="?pagenum={{pn}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">{{pn}}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page.has_next %}
                        <li class="col-md-2"><a href="?pagenum={{page.next_page_number}}&type={{typepage}}&year={{year}}&month={{month}}&category_id={{category_id}}&tag_id={{tag_id}}">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>
            </main>
{% endblock %}

end/demo2/blog/templates/single.html
{% extends 'base2.html' %}
{% block title %}
    博客实战
{% endblock %}
{% block main %}
 <main class="col-md-8">

							<article class="post post-1">
									<header class="entry-header">
											<h1 class="entry-title">{{article.title}}</h1>
											<div class="entry-meta">
													<span class="post-category"><a href="#">{{article.category.name}}</a></span>
													<span class="post-date"><a href="#"><time class="entry-date"
																							  datetime="2012-11-09T23:15:57+00:00">{{article.create_time|date:"Y-m-d"}}</time></a></span>
													<span class="post-author"><a href="#">{{article.author}}</a></span>
													<span class="comments-link"><a href="#">{{article.comment_set.count}} 评论</a></span>
													<span class="views-count"><a href="#">{{article.views}}阅读</a></span>
											</div>
									</header>
									<div class="entry-content clearfix">
										{{article.body|safe}}
									</div>
							</article>
							<section class="comment-area" id="comment-area">
									<hr>
									<h3>发表评论</h3>
									<form action="#" method="post" class="comment-form">
										{% csrf_token %}
											<div class="row">
												{% comment %}
													<div class="col-md-4">
															<label for="id_name">名字：</label>
															<input type="text" id="id_name" name="name" required>
													</div>
													<div class="col-md-4">
															<label for="id_email">邮箱：</label>
															<input type="email" id="id_email" name="email" required>
													</div>
													<div class="col-md-4">
															<label for="id_url">网址：</label>
															<input type="text" id="id_url" name="url">
													</div>
													<div class="col-md-12">
															<label for="id_comment">评论：</label>
															<textarea name="comment" id="id_comment" required></textarea>
															<button type="submit" class="comment-btn">发表</button>
													</div>
												{% endcomment %}

													<div class="col-md-4">
															<label >{{cf.name.label}}</label>
															{{cf.name}}
													</div>
													<div class="col-md-4">
															<label >{{cf.email.label}}</label>
															{{cf.email}}
													</div>
													<div class="col-md-4">
															<label >{{cf.url.label}}</label>
															{{cf.url}}
													</div>
													<div class="col-md-12">
															<label >{{cf.body.label}}</label>
															{{cf.body}}
															{{errors}}
															<button type="submit" class="comment-btn">发表</button>
													</div>

											</div>    <!-- row -->
									</form>
									<div class="comment-list-panel">
											<h3>评论列表，共 <span>{{article.comment_set.count}}</span> 条评论</h3>
											<ul class="comment-list list-unstyled">
												{% for c in article.comment_set.all %}
													<li class="comment-item">
															<span class="nickname">{{c.name}}</span>
															<time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{c.create_time|date:"Y-m-d"}}</time>
															<div class="text">
																	{{c.body}}
															</div>
													</li>
												{% endfor %}
											</ul>
									</div>
							</section>


            </main>
{% endblock %}