end/demo1/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include

# 使用媒体资源


# 路由  每个网址均需要绑定视图函数  视图函数给与页面返回

# from django.http import HttpResponse
# def index(request):
#     return HttpResponse("这里是首页")
#
# def list(request):
#     return HttpResponse("这里是列表")
#
# def jsondata(request):
#     return HttpResponse("{'name':'yxc','age':'23'}")

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('booktest.urls',namespace='booktest'))
    # 将admin和index函数绑定
    # path('index/',index),
    # path('list/',list),
    # path('jsondata/',jsondata)
    path('', include('polls.urls',namespace='polls'))


]

#  项目的所有路由地址配置文件
# 总路由配置文件


#  硬编码 在html 中有很多超级链接  其中href属性如果携程绝对路径 这种就叫做硬编码
# 在开发的过程中  可能需要反复修改路由
# 解除硬编码
# 1需要给应用一个 app_name="应用名"  下载应用的urls.py中（分路由里面）
# 2在项目路由中给应用分流时  在include中   提供命名空间
# 3在应用中给每一个路由一个名字
# 4在html中使用  href="{% url '命名空间:路由name' 实参列表 %}"
# 以前定位路由  靠总路由正则表达式+应用路由正则表达式
# 解除硬编码之后  使用  应用命名空间+应用路由名字

end/demo1/bookdemo/booktest/urls.py
from django.conf.urls import url
from . import views

app_name="booktest"

#  每个路由文件中都要有urlpatterns这个路由数组
urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^about/$',views.about,name='about'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^deletebook/(\d+)/$',views.deletebook,name='deletebook'),
    url(r'^deletehero/(\d+)/$',views.deletehero,name='deletehero'),
    url(r'^addhero/(\d+)/$',views.addhero,name='addhero'),
    url(r'^edithero/(\d+)/$',views.edithero,name='edithero'),

    url(r'^addbook/$',views.addbook,name='addbook'),
    url(r'^editbook/(\d+)/$',views.editbook,name='editbook')
]

end/demo1/bookdemo/polls/urls.py
from django.conf.urls import url
from . import views

app_name = "polls"

urlpatterns = [
    # 基于函数的路由
    url(r'^$', views.polls, name='polls'),
    url(r'^addpolls/(\d+)/$', views.addpolls, name='addpolls'),
    url(r'^ballot/(\d+)/$', views.ballot, name='ballot'),

    # 基于类的路由
    # url(r'^$', views.IndexView.as_view(), name='polls'),
    # url(r'^addpolls/(\d+)/$', views.Detailview.as_view(), name='addpolls'),
    # url(r'^ballot/(\d+)/$', views.ResultView.as_view(), name='ballot'),
    url(r'^login/$', views.login, name='login'),
    url(r'^regist/$', views.regist, name='regist'),
    url(r'^logout/$', views.logout, name='logout'),
]

end/demo1/bookdemo/booktest/models.py
from django.db import models


# Create your models here.
# 有了模型类之后模型类如何与数据库交互
# 1注册模型 在setting.py 中的INSTALLED_APPS 添加应用名
# 2生成迁移文件  用于与数据库交互 python manage.py makemigrations
# 3执行迁移 会在对应的数据库中生成对应的表  python manage.py migrate
class Book(models.Model):
    title = models.CharField(max_length=20)
    pub_date = models.DateField(default="1983-06-01")
    price=models.FloatField(default=0)

    def __str__(self):
        return self.title

class Hero(models.Model):
    name = models.CharField(max_length=20)
    gender = models.CharField(max_length=10, choices=(('male', '男'), ('female', '女')))
    content = models.CharField(max_length=100)

    # book  是一对多中的外键  on_delete代表删除主表数据是如何做响应
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class UserManager(models.Manager):
    def deleteByTelePhone(self,tele):
        user=self.get(telephone=tele)
        user.delete()


class User(models.Model):
    telephone = models.CharField(max_length=11,null=True,blank=True)
    objects=UserManager()


    def __str__(self):
        return self.telephone



# 模型类的关联关系


# 一对一   一方Account  实例a   一方Concact 实例c   关系字段定义在任意一方
# a 找 c  a.concact
# c 找 a  c.account

class Account(models.Model):
    username=models.CharField(max_length=20,verbose_name="用户名")
    password=models.CharField(max_length=20,verbose_name="密码")
    regist_date=models.DateField(auto_now_add=True,verbose_name="注册日期")


class Concact(models.Model):
    telephone=models.CharField(max_length=11,verbose_name="手机号")
    email=models.EmailField(default="1335909103@qq.com")
    account=models.OneToOneField(Account,on_delete=models.CASCADE)


# 多对多  多方Article  实例a    多方Tag 实例t   关系字段可以定义在任意一方
# 添加关系   t.articles.add(a)    移除关系  t.articles.remove(a)
# a 找 所有的 t   a.tag_set.all()   如果定义过related_name='tags' 则使用 a.tags.all()
# t 找 所有的 a   t.articles.all()
class Article(models.Model):
    title=models.CharField(max_length=20,verbose_name="标题")
    sumary=models.TextField(verbose_name="正文")

class Tag(models.Model):
    name=models.CharField(max_length=20,verbose_name="标签名")
    articles=models.ManyToManyField(Article)

end/demo1/bookdemo/polls/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    """
    自定义用户类继承django自带用户系统
    """
    telephone = models.CharField(max_length=11, verbose_name="手机号")
    pollss = models.ManyToManyField('Polls')


class Polls(models.Model):
    # 问题类
    polls_text = models.CharField(max_length=20)

    def __str__(self):
        return self.polls_text


class Pollsmsg(models.Model):
    # 选项类
    msg = models.CharField(max_length=20, verbose_name="内容")
    coutmsg = models.PositiveIntegerField(verbose_name="数量", default=0)

    polls = models.ForeignKey(Polls, on_delete=models.CASCADE)

    def __str__(self):
        return self.msg

end/demo1/bookdemo/polls/forms.py
from django import  forms
from .models import User

class LoginForm(forms.Form):
    """
    定义一个登录表单  用于生成html登录表单
    """
    username = forms.CharField(max_length=15,min_length=3,label="输入用户名",help_text="最少3，最大15")
    password = forms.CharField(max_length=15,min_length=3,widget=forms.PasswordInput,help_text="最少3，最大15")

end/demo1/bookdemo/polls/views.py
from django.shortcuts import render, redirect, reverse
from django.template import loader
from django.http import HttpResponse
from .models import Polls, Pollsmsg, User
from django.views.generic import View, TemplateView, ListView
from django.contrib.auth import authenticate, login as lin, logout as lot
from .forms import LoginForm


# Create your views here.

def polls(request):
    pollss = Polls.objects.all()
    return render(request, 'polls.html', {"pollss": pollss})


class IndexView(ListView):
    # 方法二、继承ListView
    # template_name指明使用的模板
    template_name = "polls.html"
    # queryset 指明返回的结果列表
    queryset = Polls.objects.all()
    # context_object_name 指明返回字典参数的健
    context_object_name = "pollss"

    # 方法一、继承的TemplateView
    # template_name = "polls/index.html"
    # def get_context_data(self, **kwargs):
    #     return {"questions":Question.objects.all()}


def addpolls(request, pollsid):
    # polls_text是问题   Polls是问题类
    polls_text = Polls.objects.get(id=pollsid)
    if request.method == "GET":
        print("当前用户", request.user.username)
        if request.user and request.user.username != "":

            print(request.user.pollss.all(), "11", polls_text)

            if polls_text in request.user.pollss.all():
                print("1111")
                url = reverse("polls:ballot", args=(polls_text.id,))
                return redirect(to=url)
            else:
                return render(request, 'addpolls.html', {"polls": polls_text})
        else:
            url = reverse("polls:ballot", args=(polls_text.id,))
            return redirect(to=url)
    elif request.method == "POST":
        pol1 = request.POST.get("pol")
        pollsmsg = Pollsmsg.objects.get(id=pol1)
        pollsmsg.coutmsg += 1
        pollsmsg.save()
        #  投票过后  将投票的问题传给数据库
        request.user.pollss.add(Polls.objects.get(id=pollsid))

        url = reverse("polls:ballot", args=(polls_text.id,))
        return redirect(to=url)


class Detailview(View):

    def get(self, request, pollsid):
        polls = Polls.objects.get(id=pollsid)
        return render(request, 'addpolls.html', {"polls": polls})

    def post(self, request, pollsid):
        polls = Polls.objects.get(id=pollsid)
        pol1 = request.POST.get("pol")
        pollsmsg = Pollsmsg.objects.get(id=pol1)
        pollsmsg.coutmsg += 1
        pollsmsg.save()
        url = reverse("polls:ballot", args=(polls.id,))
        return redirect(to=url)


def ballot(request, pollsid):
    polls = Polls.objects.get(id=pollsid)
    return render(request, 'ballot.html', {"polls": polls})


class ResultView(View):
    def get(self, request, pollsid):
        polls = Polls.objects.get(id=pollsid)
        return render(request, 'ballot.html', {"polls": polls})


def login(request):
    if request.method == "GET":
        # 2 使用表单类生成表单
        # lf = LoginForm()
        # return render(request, 'login.html', {"lf": lf})
        # 1 需要在html中自己编写表单
        return render(request, 'login.html')
    elif request.method == "POST":
        # lf = LoginForm(request.POST)
        # if lf.is_valid():

        username = request.POST.get("username")
        password = request.POST.get("password")
        #  可以使用Django自带的用户认证   认证成功返回用户  失败返回none
        user = authenticate(username=username, password=password)
        if user:
            # 调用Django的登录方法  生成cookie
            lin(request, user)
            url = reverse("polls:polls")
            return redirect(to=url)
        else:
            # url=reverse("polls:login")
            # return redirect(to=url)
            return render(request, 'login.html', {'errors': "用户名或密码错误"})
        # else:
        #     return HttpResponse("未知错误")


def regist(request):
    if request.method == "GET":
        return render(request, 'regist.html')
    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        password2 = request.POST.get("password2")
        if User.objects.filter(username=username).count() > 0:
            return render(request, 'regist.html', {'errors': "用户名已存在"})
        else:
            if password == password2 and password != '':
                User.objects.create_user(username=username, password=password)
                url = reverse("polls:login")
                return redirect(to=url)
            else:
                return render(request, 'regist.html', {'errors': "密码错误"})


def logout(request):
    #  调用Django的登出方法  为了删除cookie
    lot(request)
    url = reverse("polls:polls")
    return redirect(to=url)

end/demo1/bookdemo/templates/addbook.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        <div>
            <h1>添加书籍</h1>
            <form action="" method="post">
                {% csrf_token %}
                书籍名称：<input type="text" name="booktitle" value="none">
                <br>
                出版日期：<input type="date" name="bookdate" value="1983-06-01">
                <br>
                价格：<input type="number" name="booknum" value="0">
                <br>
                <input type="submit" value="提交">
            </form>
        </div>
</body>
</html>

end/demo1/bookdemo/templates/addhero.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>添加英雄</title>
</head>
<body>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                英雄名字：<input type="text" name="heroname" placeholder="输入角色名">
                <br>
                英雄技能：<input type="text" name="herocontent" placeholder="输入技能">
                <br>
                性别：<input type="radio" value="male" checked name="sex"> 男 <input type="radio" value="female" checked name="sex">女
                <input type="submit" value="提交">
            </form>

        </div>
</body>
</html>

end/demo1/bookdemo/templates/addpolls.html
{% extends 'base.html' %}
{% block body %}
    <div>

        <h1>投票信息：{{polls.polls_text}}</h1>
        <form action="" method="post">
                {% csrf_token %}
                {% for pollsmsg in polls.pollsmsg_set.all %}
                <input type="radio" name="pol" value="{{pollsmsg.id}}">{{pollsmsg.msg}}
                <br>
                {% endfor %}
                <input type="submit" value="投票">

        </form>
        <a href="{% url 'polls:polls' %}">返回</a>
    </div>
{% endblock %}

{% block footer %}
    底部
{% endblock %}

end/demo1/bookdemo/templates/ballot.html
{% extends 'base.html' %}


        {% block body %}
            <h1>投票信息：{{polls.polls_text}}</h1>
                {% for pollsmsg in polls.pollsmsg_set.all %}
                    {{pollsmsg.msg}}: {{pollsmsg.coutmsg}}
                    <br>
                {% endfor %}
            <a href="/">返回主页</a>
        {% endblock %}

        {% block footer %}
            底部
        {% endblock %}

end/demo1/bookdemo/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        <div>
            {% block header %}
                <div>
                    {% if request.user and request.user.username != '' %}
                    用户名:{{request.user.username}} <a href="{% url 'polls:logout' %}">退出</a>
                    {% else %}
                        <a href="{% url 'polls:login' %}">登录</a> <a href="{% url 'polls:regist' %}"> 注册</a>
                    {% endif %}
                </div>
            {% endblock %}

            {% block body %}
                身体
            {% endblock %}

            {% block footer %}
                底部
            {% endblock %}
        </div>
</body>
</html>

end/demo1/bookdemo/templates/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
    <h1>这里是详情页</h1>
    <div>书名：{{book.title}}</div>
    <ul>
        {% for hero in book.hero_set.all %}
            <li>{{hero.name}}--{{hero.content}} &nbsp;&nbsp;&nbsp;
                <a href="{% url 'booktest:edithero' hero.id %}">编辑</a>
                <a href="{% url 'booktest:deletehero' hero.id %}">删除</a>
            </li>

        {% endfor %}
    </ul>
    <ul>
        {# <a href="/">返回</a> #}
        <a href="{% url 'booktest:addhero' book.id %}">添加</a>
        <a href="{% url 'booktest:index' %}">返回</a>
    </ul>
</body>
</html>

end/demo1/bookdemo/templates/editbook.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        <div>
            <h2>编辑书籍</h2>

            <form action="" method="post">
                {% csrf_token %}
                书籍名称：<input type="text" name="booktitle" value="{{book.title}}">
                <br>
                出版日期：<input type="date" name="bookdate" value="{{book.pub_date}}">
                <br>
                价格: <input type="number" name="booknum" value="{{book.price}}">
                <br>
                <input type="submit" value="提交">
            </form>

        </div>
</body>
</html>

end/demo1/bookdemo/templates/edithero.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>编辑英雄</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    英雄的名字：<input type="text" name="heroname" value="{{hero.name}}">
    <br>
    英雄的技能：<input type="text" name="herocontent" value="{{hero.content}}">
    <br>
    {% if hero.gender == 'male' %}
    英雄的性别：<input type="radio" name="sex" value="male" checked>男<input type="radio" name="sex" value="female">女
    {% else %}
    英雄的性别：<input type="radio" name="sex" value="male">男<input type="radio" name="sex" value="female" checked>女
    {% endif %}
    <br>
    <input type="submit" value="提交">
</form>
</body>
</html>

end/demo1/bookdemo/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
    <h1>这里是首页</h1>
    <div>
        <h2>书籍</h2>
        <ul>
            {% for book in books %}
                {# 这种是django的模板注释相较于ctrl+/  这种注释在页面f12的时候  不会显示 #}
                {# <a href="/detail/{{book.id}}/"><li>{{book.id}}--{{book.title}}--{{book.price}}--{{book.pub_date}}</li></a> #}
                <li><a href="{% url 'booktest:detail' book.id %}">{{book.id}}--{{book.title}}--{{book.price}}--{{book.pub_date}}</a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="{% url 'booktest:editbook' book.id %}">编辑</a> &nbsp;&nbsp;&nbsp;
                    <a href="{% url 'booktest:deletebook' book.id %}">删除</a></li>
            {% endfor %}
        </ul>
        <a href="addbook/">添加书籍</a>
    </div>
</body>
</html>

end/demo1/bookdemo/templates/login.html
{% block body %}

{% comment %}
<form action="#" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username">
    <br>
    密码: <input type="password" name="password">
    <br>
    <input type="submit" value="登录">
    {{errors}}
</form>
{% endcomment %}

<form action="" method="post">
    {% csrf_token %}
    {# {{lf}} #}

    {{lf.username.label}}:{{lf.username}}
    <br>
    {{lf.username.help_text}}
    <br>
    {{lf.password.label}}:{{lf.password}}
    <br>
    {{lf.username.help_text}}
    <br>

    <input type="submit" value="登录">

</form>

{% endblock %}

end/demo1/bookdemo/templates/polls.html
{% extends 'base.html' %}
         {% block header %}
                <div>

                    {% if request.user and request.user.username != '' %}
                    用户名:{{request.user.username}} <a href="{% url 'polls:logout' %}">退出</a>
                    {% else %}
                        <a href="{% url 'polls:login' %}">登录</a> <a href="{% url 'polls:regist' %}">注册</a>
                    {% endif %}
                </div>
            {% endblock %}

            {% block body %}
                 <div>

                    <h1>投票信息汇总</h1>
                    <ul>
                        {% for polls in pollss %}

                        <li><a href="{% url 'polls:addpolls' polls.id %}">{{polls.id}}.{{polls.polls_text}}</a></li>

                        {% endfor %}
                    </ul>


                </div>
            {% endblock %}

            {% block footer %}
                底部
            {% endblock %}

end/demo1/bookdemo/templates/regist.html
{% block body %}


<form action="#" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username">
    <br>
    密码: <input type="password" name="password">
    <br>
    重复密码: <input type="password" name="password2">
    <br>
    <input type="submit" value="登录">
    {{errors}}
</form>


{% endblock %}